//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOTP.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UI {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UI() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TOTP.Resources.UI", typeof(UI).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error adding new TOTP.
        /// </summary>
        internal static string ex_Adding_New_TOTP {
            get {
                return ResourceManager.GetString("ex_Adding_New_TOTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup failed: {0}.
        /// </summary>
        internal static string ex_BackupFailed {
            get {
                return ResourceManager.GetString("ex_BackupFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error deleting secret.
        /// </summary>
        internal static string ex_DeletingSecret {
            get {
                return ResourceManager.GetString("ex_DeletingSecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error deleting secret:{0}.
        /// </summary>
        internal static string ex_DeletingSecret_0 {
            get {
                return ResourceManager.GetString("ex_DeletingSecret_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error generating TOTP code.
        /// </summary>
        internal static string ex_Error_Generating_TOTP {
            get {
                return ResourceManager.GetString("ex_Error_Generating_TOTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error generating TOTP code for {0}: {1}.
        /// </summary>
        internal static string ex_Error_Generating_TOTP_0_0 {
            get {
                return ResourceManager.GetString("ex_Error_Generating_TOTP_0_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A fatal application error occurred. The app must now close.\n\nSee log files for details..
        /// </summary>
        internal static string ex_FatalError {
            get {
                return ResourceManager.GetString("ex_FatalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error filtering secrets.
        /// </summary>
        internal static string ex_Filtering_Secrets {
            get {
                return ResourceManager.GetString("ex_Filtering_Secrets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid secret format. Please ensure it is a valid Base32 string.
        /// </summary>
        internal static string ex_InvalidSecret {
            get {
                return ResourceManager.GetString("ex_InvalidSecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error selecting secret.
        /// </summary>
        internal static string ex_Selecting_Secret {
            get {
                return ResourceManager.GetString("ex_Selecting_Secret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error.
        /// </summary>
        internal static string ex_UnexpectedError {
            get {
                return ResourceManager.GetString("ex_UnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error updating secret.
        /// </summary>
        internal static string ex_UpdatingSecret {
            get {
                return ResourceManager.GetString("ex_UpdatingSecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error updating secret:{0}.
        /// </summary>
        internal static string ex_UpdatingSecret_0 {
            get {
                return ResourceManager.GetString("ex_UpdatingSecret_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOTP Manager is starting....
        /// </summary>
        internal static string msg_Application_Starting {
            get {
                return ResourceManager.GetString("msg_Application_Starting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A background task failed. You can continue using the application..
        /// </summary>
        internal static string msg_BackroundTaskException {
            get {
                return ResourceManager.GetString("msg_BackroundTaskException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete account: &quot;{0}&quot;?.
        /// </summary>
        internal static string msg_ConfirmDeleteSecret {
            get {
                return ResourceManager.GetString("msg_ConfirmDeleteSecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred.\n\nYou can continue using the application, but some features may not work correctly..
        /// </summary>
        internal static string msg_DispatcherException {
            get {
                return ResourceManager.GetString("msg_DispatcherException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during shutdown: {0}.
        /// </summary>
        internal static string msg_Error_Shutdown {
            get {
                return ResourceManager.GetString("msg_Error_Shutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during startup of TOTP Manager.
        /// </summary>
        internal static string msg_Error_Starting_App {
            get {
                return ResourceManager.GetString("msg_Error_Starting_App", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error parsing OTP URL.
        /// </summary>
        internal static string msg_ErrorParsingOtpUrl {
            get {
                return ResourceManager.GetString("msg_ErrorParsingOtpUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete the secret.
        /// </summary>
        internal static string msg_Failed_Delete_Secret {
            get {
                return ResourceManager.GetString("msg_Failed_Delete_Secret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load secrets.
        /// </summary>
        internal static string msg_Failed_Loading_Secrets {
            get {
                return ResourceManager.GetString("msg_Failed_Loading_Secrets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save changes.
        /// </summary>
        internal static string msg_Failed_Saving_Changes {
            get {
                return ResourceManager.GetString("msg_Failed_Saving_Changes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save the secret.
        /// </summary>
        internal static string msg_Failed_Storage {
            get {
                return ResourceManager.GetString("msg_Failed_Storage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed updating secret.
        /// </summary>
        internal static string msg_Failed_Updating_Secret {
            get {
                return ResourceManager.GetString("msg_Failed_Updating_Secret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to add secret: {0}.
        /// </summary>
        internal static string msg_FailedAddingSecret {
            get {
                return ResourceManager.GetString("msg_FailedAddingSecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load secrets: {0}.
        /// </summary>
        internal static string msg_FailedReadingSecrets {
            get {
                return ResourceManager.GetString("msg_FailedReadingSecrets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to platform &apos;{0}&apos; already exists.
        /// </summary>
        internal static string msg_Platform_Exists {
            get {
                return ResourceManager.GetString("msg_Platform_Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to platform not found.
        /// </summary>
        internal static string msg_Platform_Not_Found {
            get {
                return ResourceManager.GetString("msg_Platform_Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to platform &apos;{0}&apos; not found..
        /// </summary>
        internal static string msg_PlatformNotFound_0 {
            get {
                return ResourceManager.GetString("msg_PlatformNotFound_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to platform is required..
        /// </summary>
        internal static string msg_PlatformRequired {
            get {
                return ResourceManager.GetString("msg_PlatformRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to platform and Secret cannot be empty.
        /// </summary>
        internal static string msg_PlatformSecretNotEmpty {
            get {
                return ResourceManager.GetString("msg_PlatformSecretNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secret must be a valid Base32 string.
        /// </summary>
        internal static string msg_SecretInvalidFormat {
            get {
                return ResourceManager.GetString("msg_SecretInvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secret is required..
        /// </summary>
        internal static string msg_SecretRequired {
            get {
                return ResourceManager.GetString("msg_SecretRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secret updated successfully.
        /// </summary>
        internal static string msg_SecretUpdated {
            get {
                return ResourceManager.GetString("msg_SecretUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new account.
        /// </summary>
        internal static string tooltip_AddNew {
            get {
                return ResourceManager.GetString("tooltip_AddNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan the code with your authenticator app.
        /// </summary>
        internal static string tooltip_AuthenticatorAppScan {
            get {
                return ResourceManager.GetString("tooltip_AuthenticatorAppScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string ui_btnAdd {
            get {
                return ResourceManager.GetString("ui_btnAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string ui_btnCancel {
            get {
                return ResourceManager.GetString("ui_btnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string ui_btnDelete {
            get {
                return ResourceManager.GetString("ui_btnDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string ui_btnEdit {
            get {
                return ResourceManager.GetString("ui_btnEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string ui_btnOK {
            get {
                return ResourceManager.GetString("ui_btnOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string ui_btnSave {
            get {
                return ResourceManager.GetString("ui_btnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan QR code.
        /// </summary>
        internal static string ui_btnScan {
            get {
                return ResourceManager.GetString("ui_btnScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string ui_btnSearch {
            get {
                return ResourceManager.GetString("ui_btnSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing camera....
        /// </summary>
        internal static string ui_CameraInit {
            get {
                return ResourceManager.GetString("ui_CameraInit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ui_Caption_Error {
            get {
                return ResourceManager.GetString("ui_Caption_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        internal static string ui_Caption_Info {
            get {
                return ResourceManager.GetString("ui_Caption_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention.
        /// </summary>
        internal static string ui_Caption_Warning {
            get {
                return ResourceManager.GetString("ui_Caption_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copied!.
        /// </summary>
        internal static string ui_Code_Copied_Clipboard {
            get {
                return ResourceManager.GetString("ui_Code_Copied_Clipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change entry.
        /// </summary>
        internal static string ui_Edit_Entry {
            get {
                return ResourceManager.GetString("ui_Edit_Entry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export all accounts to file.
        /// </summary>
        internal static string ui_Export {
            get {
                return ResourceManager.GetString("ui_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show QR code.
        /// </summary>
        internal static string ui_GenerateQR_Code {
            get {
                return ResourceManager.GetString("ui_GenerateQR_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to account.
        /// </summary>
        internal static string ui_Header_Account {
            get {
                return ResourceManager.GetString("ui_Header_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to platform.
        /// </summary>
        internal static string ui_Header_Platform {
            get {
                return ResourceManager.GetString("ui_Header_Platform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point your QR code at the camera.
        /// </summary>
        internal static string ui_Header_QR_Window {
            get {
                return ResourceManager.GetString("ui_Header_QR_Window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to secret.
        /// </summary>
        internal static string ui_Header_Secret {
            get {
                return ResourceManager.GetString("ui_Header_Secret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to secret key.
        /// </summary>
        internal static string ui_Header_Secret_Shared {
            get {
                return ResourceManager.GetString("ui_Header_Secret_Shared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to account (optional).
        /// </summary>
        internal static string ui_label_account {
            get {
                return ResourceManager.GetString("ui_label_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to username or email.
        /// </summary>
        internal static string ui_label_account_watermark {
            get {
                return ResourceManager.GetString("ui_label_account_watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to base32-encoded string.
        /// </summary>
        internal static string ui_label_base32_string {
            get {
                return ResourceManager.GetString("ui_label_base32_string", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string ui_label_Search {
            get {
                return ResourceManager.GetString("ui_label_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search....
        /// </summary>
        internal static string ui_label_Search_Dots {
            get {
                return ResourceManager.GetString("ui_label_Search_Dots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string ui_Options {
            get {
                return ResourceManager.GetString("ui_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan QR Code.
        /// </summary>
        internal static string ui_ScanQR {
            get {
                return ResourceManager.GetString("ui_ScanQR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock session when ....
        /// </summary>
        internal static string ui_Settings_Auth_Lock_Session {
            get {
                return ResourceManager.GetString("ui_Settings_Auth_Lock_Session", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization type.
        /// </summary>
        internal static string ui_Settings_Auth_Method {
            get {
                return ResourceManager.GetString("ui_Settings_Auth_Method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string ui_Settings_Auth_Password {
            get {
                return ResourceManager.GetString("ui_Settings_Auth_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        internal static string ui_Settings_Auth_Password_SetChange {
            get {
                return ResourceManager.GetString("ui_Settings_Auth_Password_SetChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Hello.
        /// </summary>
        internal static string ui_Settings_Auth_WindowsHello {
            get {
                return ResourceManager.GetString("ui_Settings_Auth_WindowsHello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear clipboard.
        /// </summary>
        internal static string ui_Settings_ClearClipboard {
            get {
                return ResourceManager.GetString("ui_Settings_ClearClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to after.
        /// </summary>
        internal static string ui_Settings_ClearClipboard_After {
            get {
                return ResourceManager.GetString("ui_Settings_ClearClipboard_After", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seconds.
        /// </summary>
        internal static string ui_Settings_ClearClipboard_Seconds {
            get {
                return ResourceManager.GetString("ui_Settings_ClearClipboard_Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows lock screen.
        /// </summary>
        internal static string ui_Settings_LockOnWindowsLock {
            get {
                return ResourceManager.GetString("ui_Settings_LockOnWindowsLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization.
        /// </summary>
        internal static string ui_Settings_Tab_Authorization {
            get {
                return ResourceManager.GetString("ui_Settings_Tab_Authorization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        internal static string ui_Settings_Tab_Export {
            get {
                return ResourceManager.GetString("ui_Settings_Tab_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string ui_Settings_Title {
            get {
                return ResourceManager.GetString("ui_Settings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to i.e. github, msft, ....
        /// </summary>
        internal static string ui_watermark_platform {
            get {
                return ResourceManager.GetString("ui_watermark_platform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add new platform.
        /// </summary>
        internal static string ui_Window_Title_PlatformSecretDialog {
            get {
                return ResourceManager.GetString("ui_Window_Title_PlatformSecretDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOTP Manager.
        /// </summary>
        internal static string ui_Window_Title_TOTP_Manager {
            get {
                return ResourceManager.GetString("ui_Window_Title_TOTP_Manager", resourceCulture);
            }
        }
    }
}
