//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOTP.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UI {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UI() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TOTP.Resources.UI", typeof(UI).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application settings could not be decrypted..
        /// </summary>
        internal static string err_AppSettingsDecryptFailed {
            get {
                return ResourceManager.GetString("err_AppSettingsDecryptFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application settings are invalid..
        /// </summary>
        internal static string err_AppSettingsDeserializeFailed {
            get {
                return ResourceManager.GetString("err_AppSettingsDeserializeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application settings could not be encrypted..
        /// </summary>
        internal static string err_AppSettingsEncryptFailed {
            get {
                return ResourceManager.GetString("err_AppSettingsEncryptFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access to application settings was denied..
        /// </summary>
        internal static string err_AppSettingsLoadAccessDenied {
            get {
                return ResourceManager.GetString("err_AppSettingsLoadAccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application settings could not be loaded..
        /// </summary>
        internal static string err_AppSettingsLoadFailed {
            get {
                return ResourceManager.GetString("err_AppSettingsLoadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application settings could not be saved due to missing permissions..
        /// </summary>
        internal static string err_AppSettingsSaveAccessDenied {
            get {
                return ResourceManager.GetString("err_AppSettingsSaveAccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application settings could not be saved..
        /// </summary>
        internal static string err_AppSettingsSaveFailed {
            get {
                return ResourceManager.GetString("err_AppSettingsSaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export data could not be encrypted..
        /// </summary>
        internal static string err_ExportEncryptionFailed {
            get {
                return ResourceManager.GetString("err_ExportEncryptionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export failed because file access was denied..
        /// </summary>
        internal static string err_ExportFileAccessDenied {
            get {
                return ResourceManager.GetString("err_ExportFileAccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The export file could not be written..
        /// </summary>
        internal static string err_ExportFileWriteFailed {
            get {
                return ResourceManager.GetString("err_ExportFileWriteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export failed due to an unexpected error..
        /// </summary>
        internal static string err_ExportUnknownFailed {
            get {
                return ResourceManager.GetString("err_ExportUnknownFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected import file could not be found..
        /// </summary>
        internal static string err_ImportFileNotFound {
            get {
                return ResourceManager.GetString("err_ImportFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected file is not a valid import file..
        /// </summary>
        internal static string err_ImportInvalidFile {
            get {
                return ResourceManager.GetString("err_ImportInvalidFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import failed, file content invalid..
        /// </summary>
        internal static string err_ImportInvalidPayload {
            get {
                return ResourceManager.GetString("err_ImportInvalidPayload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import failed, unexpected error..
        /// </summary>
        internal static string err_ImportUnknownFailed {
            get {
                return ResourceManager.GetString("err_ImportUnknownFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong password or corrupted file..
        /// </summary>
        internal static string err_ImportWrongPasswordOrTampered {
            get {
                return ResourceManager.GetString("err_ImportWrongPasswordOrTampered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The token &apos;{0}&apos; could not be created..
        /// </summary>
        internal static string err_OtpCreateFailed {
            get {
                return ResourceManager.GetString("err_OtpCreateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The token &apos;{0}&apos; could not be deleted..
        /// </summary>
        internal static string err_OtpDeleteFailed {
            get {
                return ResourceManager.GetString("err_OtpDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage access was denied..
        /// </summary>
        internal static string err_OtpStorageAccessDenied {
            get {
                return ResourceManager.GetString("err_OtpStorageAccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The storage backup could not be created..
        /// </summary>
        internal static string err_OtpStorageBackupFailed {
            get {
                return ResourceManager.GetString("err_OtpStorageBackupFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stored token data could not be decrypted..
        /// </summary>
        internal static string err_OtpStorageDecryptFailed {
            get {
                return ResourceManager.GetString("err_OtpStorageDecryptFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token data could not be encrypted before saving..
        /// </summary>
        internal static string err_OtpStorageEncryptionFailed {
            get {
                return ResourceManager.GetString("err_OtpStorageEncryptionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tokens could not be loaded from storage..
        /// </summary>
        internal static string err_OtpStorageReadFailed {
            get {
                return ResourceManager.GetString("err_OtpStorageReadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tokens could not be saved to storage..
        /// </summary>
        internal static string err_OtpStorageWriteFailed {
            get {
                return ResourceManager.GetString("err_OtpStorageWriteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The token &apos;{0}&apos; could not be updated..
        /// </summary>
        internal static string err_OtpUpdateFailed {
            get {
                return ResourceManager.GetString("err_OtpUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application settings could not be loaded by the settings service..
        /// </summary>
        internal static string err_SettingsServiceLoadFailed {
            get {
                return ResourceManager.GetString("err_SettingsServiceLoadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application settings could not be saved by the settings service..
        /// </summary>
        internal static string err_SettingsServiceSaveFailed {
            get {
                return ResourceManager.GetString("err_SettingsServiceSaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The token could not be created..
        /// </summary>
        internal static string err_TokensCreateFailed {
            get {
                return ResourceManager.GetString("err_TokensCreateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The token could not be deleted..
        /// </summary>
        internal static string err_TokensDeleteFailed {
            get {
                return ResourceManager.GetString("err_TokensDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tokens could not be loaded..
        /// </summary>
        internal static string err_TokensLoadFailed {
            get {
                return ResourceManager.GetString("err_TokensLoadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The token could not be updated..
        /// </summary>
        internal static string err_TokensUpdateFailed {
            get {
                return ResourceManager.GetString("err_TokensUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred..
        /// </summary>
        internal static string err_Unknown {
            get {
                return ResourceManager.GetString("err_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error adding new TOTP.
        /// </summary>
        internal static string ex_Adding_New_TOTP {
            get {
                return ResourceManager.GetString("ex_Adding_New_TOTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error deleting secret.
        /// </summary>
        internal static string ex_DeletingSecret {
            get {
                return ResourceManager.GetString("ex_DeletingSecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error deleting secret:{0}.
        /// </summary>
        internal static string ex_DeletingSecret_0 {
            get {
                return ResourceManager.GetString("ex_DeletingSecret_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error generating TOTP code.
        /// </summary>
        internal static string ex_Error_Generating_TOTP {
            get {
                return ResourceManager.GetString("ex_Error_Generating_TOTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A fatal application error occurred. The app must now close.\n\nSee log files for details..
        /// </summary>
        internal static string ex_FatalError {
            get {
                return ResourceManager.GetString("ex_FatalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error filtering secrets.
        /// </summary>
        internal static string ex_Filtering_Secrets {
            get {
                return ResourceManager.GetString("ex_Filtering_Secrets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error selecting secret.
        /// </summary>
        internal static string ex_Selecting_Secret {
            get {
                return ResourceManager.GetString("ex_Selecting_Secret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error.
        /// </summary>
        internal static string ex_UnexpectedError {
            get {
                return ResourceManager.GetString("ex_UnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error updating secret.
        /// </summary>
        internal static string ex_UpdatingSecret {
            get {
                return ResourceManager.GetString("ex_UpdatingSecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error updating secret:{0}.
        /// </summary>
        internal static string ex_UpdatingSecret_0 {
            get {
                return ResourceManager.GetString("ex_UpdatingSecret_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A background task failed. You can continue using the application..
        /// </summary>
        internal static string msg_BackroundTaskException {
            get {
                return ResourceManager.GetString("msg_BackroundTaskException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token: &quot;{0}&quot;.
        /// </summary>
        internal static string msg_ConfirmDeleteSecret {
            get {
                return ResourceManager.GetString("msg_ConfirmDeleteSecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred.\n\nYou can continue using the application, but some features may not work correctly..
        /// </summary>
        internal static string msg_DispatcherException {
            get {
                return ResourceManager.GetString("msg_DispatcherException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error parsing OTP URL.
        /// </summary>
        internal static string msg_ErrorParsingOtpUrl {
            get {
                return ResourceManager.GetString("msg_ErrorParsingOtpUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to platform &apos;{0}&apos; already exists.
        /// </summary>
        internal static string msg_Platform_Exists {
            get {
                return ResourceManager.GetString("msg_Platform_Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to platform is required..
        /// </summary>
        internal static string msg_PlatformRequired {
            get {
                return ResourceManager.GetString("msg_PlatformRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secret must be a valid Base32 string.
        /// </summary>
        internal static string msg_SecretInvalidFormat {
            get {
                return ResourceManager.GetString("msg_SecretInvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secret is required..
        /// </summary>
        internal static string msg_SecretRequired {
            get {
                return ResourceManager.GetString("msg_SecretRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new token.
        /// </summary>
        internal static string tooltip_AddNew {
            get {
                return ResourceManager.GetString("tooltip_AddNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan the code with your authenticator app.
        /// </summary>
        internal static string tooltip_AuthenticatorAppScan {
            get {
                return ResourceManager.GetString("tooltip_AuthenticatorAppScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to copy.
        /// </summary>
        internal static string tooltip_ClickToCopyCode {
            get {
                return ResourceManager.GetString("tooltip_ClickToCopyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string ui_btnAdd {
            get {
                return ResourceManager.GetString("ui_btnAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string ui_btnCancel {
            get {
                return ResourceManager.GetString("ui_btnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string ui_btnDelete {
            get {
                return ResourceManager.GetString("ui_btnDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string ui_btnDetails {
            get {
                return ResourceManager.GetString("ui_btnDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string ui_btnEdit {
            get {
                return ResourceManager.GetString("ui_btnEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string ui_btnOK {
            get {
                return ResourceManager.GetString("ui_btnOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string ui_btnSave {
            get {
                return ResourceManager.GetString("ui_btnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan QR code.
        /// </summary>
        internal static string ui_btnScan {
            get {
                return ResourceManager.GetString("ui_btnScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string ui_btnSearch {
            get {
                return ResourceManager.GetString("ui_btnSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing camera....
        /// </summary>
        internal static string ui_CameraInit {
            get {
                return ResourceManager.GetString("ui_CameraInit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ui_Caption_Error {
            get {
                return ResourceManager.GetString("ui_Caption_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        internal static string ui_Caption_Info {
            get {
                return ResourceManager.GetString("ui_Caption_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention.
        /// </summary>
        internal static string ui_Caption_Warning {
            get {
                return ResourceManager.GetString("ui_Caption_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change entry.
        /// </summary>
        internal static string ui_Edit_Entry {
            get {
                return ResourceManager.GetString("ui_Edit_Entry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter password for encrypted import.
        /// </summary>
        internal static string ui_EnterImportPassword {
            get {
                return ResourceManager.GetString("ui_EnterImportPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export all tokens to file.
        /// </summary>
        internal static string ui_Export {
            get {
                return ResourceManager.GetString("ui_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password required.
        /// </summary>
        internal static string ui_ExportPasswordRequired {
            get {
                return ResourceManager.GetString("ui_ExportPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm custom export password.
        /// </summary>
        internal static string ui_ExportPwd_ConfirmCustomPasswordLabel {
            get {
                return ResourceManager.GetString("ui_ExportPwd_ConfirmCustomPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom export password.
        /// </summary>
        internal static string ui_ExportPwd_CustomPasswordLabel {
            get {
                return ResourceManager.GetString("ui_ExportPwd_CustomPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom password and confirmation do not match..
        /// </summary>
        internal static string ui_ExportPwd_CustomPasswordMismatch {
            get {
                return ResourceManager.GetString("ui_ExportPwd_CustomPasswordMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current master password.
        /// </summary>
        internal static string ui_ExportPwd_MasterPasswordLabel {
            get {
                return ResourceManager.GetString("ui_ExportPwd_MasterPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose way of encryption.
        /// </summary>
        internal static string ui_ExportPwd_PromptMessage {
            get {
                return ResourceManager.GetString("ui_ExportPwd_PromptMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use custom export password.
        /// </summary>
        internal static string ui_ExportPwd_UseCustomOption {
            get {
                return ResourceManager.GetString("ui_ExportPwd_UseCustomOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use current master password.
        /// </summary>
        internal static string ui_ExportPwd_UseMasterOption {
            get {
                return ResourceManager.GetString("ui_ExportPwd_UseMasterOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong master password..
        /// </summary>
        internal static string ui_ExportPwd_WrongMasterPassword {
            get {
                return ResourceManager.GetString("ui_ExportPwd_WrongMasterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show QR code.
        /// </summary>
        internal static string ui_GenerateQR_Code {
            get {
                return ResourceManager.GetString("ui_GenerateQR_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to token.
        /// </summary>
        internal static string ui_Header_Account {
            get {
                return ResourceManager.GetString("ui_Header_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to platform.
        /// </summary>
        internal static string ui_Header_Platform {
            get {
                return ResourceManager.GetString("ui_Header_Platform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point your QR code at the camera.
        /// </summary>
        internal static string ui_Header_QR_Window {
            get {
                return ResourceManager.GetString("ui_Header_QR_Window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to secret.
        /// </summary>
        internal static string ui_Header_Secret {
            get {
                return ResourceManager.GetString("ui_Header_Secret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No entries found in selected import file..
        /// </summary>
        internal static string ui_Import_NoEntriesFound {
            get {
                return ResourceManager.GetString("ui_Import_NoEntriesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \nImport preview:\n\nTotal entries: {0}\nConflicts with existing: {1}\nSelected strategy: {2}\n\nProjected result:\n\nAdd: {3}, \nReplace: {4}, \nSkip: {5}\n\nContinue with import?.
        /// </summary>
        internal static string ui_Import_PreviewSummary {
            get {
                return ResourceManager.GetString("ui_Import_PreviewSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import processed {0} entries. \n\nAdded: {1}, \nReplaced: {2}, \nSkipped: {3}, \nFailed: {4}..
        /// </summary>
        internal static string ui_Import_ResultSummary {
            get {
                return ResourceManager.GetString("ui_Import_ResultSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required.
        /// </summary>
        internal static string ui_ImportPasswordRequired {
            get {
                return ResourceManager.GetString("ui_ImportPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search....
        /// </summary>
        internal static string ui_label_Search_Dots {
            get {
                return ResourceManager.GetString("ui_label_Search_Dots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password changed successfully..
        /// </summary>
        internal static string ui_Password_ChangeSuccess {
            get {
                return ResourceManager.GetString("ui_Password_ChangeSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm the password..
        /// </summary>
        internal static string ui_Password_ConfirmRequired {
            get {
                return ResourceManager.GetString("ui_Password_ConfirmRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be at least {0} characters..
        /// </summary>
        internal static string ui_Password_MinLength_Format {
            get {
                return ResourceManager.GetString("ui_Password_MinLength_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords do not match..
        /// </summary>
        internal static string ui_Password_Mismatch {
            get {
                return ResourceManager.GetString("ui_Password_Mismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required..
        /// </summary>
        internal static string ui_Password_Required {
            get {
                return ResourceManager.GetString("ui_Password_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password setup failed. Check the password requirements..
        /// </summary>
        internal static string ui_Password_SetupFailed {
            get {
                return ResourceManager.GetString("ui_Password_SetupFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password validation failed..
        /// </summary>
        internal static string ui_Password_ValidationFailed {
            get {
                return ResourceManager.GetString("ui_Password_ValidationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password verification failed..
        /// </summary>
        internal static string ui_Password_VerificationFailed {
            get {
                return ResourceManager.GetString("ui_Password_VerificationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan QR Code.
        /// </summary>
        internal static string ui_ScanQR {
            get {
                return ResourceManager.GetString("ui_ScanQR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOTP Manager.
        /// </summary>
        internal static string ui_Settings_About_AppName {
            get {
                return ResourceManager.GetString("ui_Settings_About_AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly version.
        /// </summary>
        internal static string ui_Settings_About_AssemblyVersion {
            get {
                return ResourceManager.GetString("ui_Settings_About_AssemblyVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for updates.
        /// </summary>
        internal static string ui_Settings_About_CheckForUpdates {
            get {
                return ResourceManager.GetString("ui_Settings_About_CheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for updates....
        /// </summary>
        internal static string ui_Settings_About_CheckingForUpdates {
            get {
                return ResourceManager.GetString("ui_Settings_About_CheckingForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desktop authenticator with signed in-app updates..
        /// </summary>
        internal static string ui_Settings_About_Description {
            get {
                return ResourceManager.GetString("ui_Settings_About_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation path.
        /// </summary>
        internal static string ui_Settings_About_InstallationPath {
            get {
                return ResourceManager.GetString("ui_Settings_About_InstallationPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running version.
        /// </summary>
        internal static string ui_Settings_About_RunningVersion {
            get {
                return ResourceManager.GetString("ui_Settings_About_RunningVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software updates.
        /// </summary>
        internal static string ui_Settings_About_SoftwareUpdates {
            get {
                return ResourceManager.GetString("ui_Settings_About_SoftwareUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checks GitHub for a newer signed release and opens the updater flow if one is available..
        /// </summary>
        internal static string ui_Settings_About_SoftwareUpdatesDescription {
            get {
                return ResourceManager.GetString("ui_Settings_About_SoftwareUpdatesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock session when ....
        /// </summary>
        internal static string ui_Settings_Auth_Lock_Session {
            get {
                return ResourceManager.GetString("ui_Settings_Auth_Lock_Session", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization type.
        /// </summary>
        internal static string ui_Settings_Auth_Method {
            get {
                return ResourceManager.GetString("ui_Settings_Auth_Method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string ui_Settings_Auth_Password {
            get {
                return ResourceManager.GetString("ui_Settings_Auth_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        internal static string ui_Settings_Auth_Password_SetChange {
            get {
                return ResourceManager.GetString("ui_Settings_Auth_Password_SetChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Hello.
        /// </summary>
        internal static string ui_Settings_Auth_WindowsHello {
            get {
                return ResourceManager.GetString("ui_Settings_Auth_WindowsHello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear clipboard.
        /// </summary>
        internal static string ui_Settings_ClearClipboard {
            get {
                return ResourceManager.GetString("ui_Settings_ClearClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to after.
        /// </summary>
        internal static string ui_Settings_ClearClipboard_After {
            get {
                return ResourceManager.GetString("ui_Settings_ClearClipboard_After", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seconds.
        /// </summary>
        internal static string ui_Settings_ClearClipboard_Seconds {
            get {
                return ResourceManager.GetString("ui_Settings_ClearClipboard_Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export tokens.
        /// </summary>
        internal static string ui_Settings_Export {
            get {
                return ResourceManager.GetString("ui_Settings_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export encrypted.
        /// </summary>
        internal static string ui_Settings_Export_Encrypt {
            get {
                return ResourceManager.GetString("ui_Settings_Export_Encrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format.
        /// </summary>
        internal static string ui_Settings_Export_Format {
            get {
                return ResourceManager.GetString("ui_Settings_Export_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open exported file after export.
        /// </summary>
        internal static string ui_Settings_Export_OpenAfterExport {
            get {
                return ResourceManager.GetString("ui_Settings_Export_OpenAfterExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export successful.
        /// </summary>
        internal static string ui_Settings_Export_Success {
            get {
                return ResourceManager.GetString("ui_Settings_Export_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import tokens.
        /// </summary>
        internal static string ui_Settings_Import {
            get {
                return ResourceManager.GetString("ui_Settings_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep both.
        /// </summary>
        internal static string ui_Settings_Import_Conflict_KeepBoth {
            get {
                return ResourceManager.GetString("ui_Settings_Import_Conflict_KeepBoth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace existing.
        /// </summary>
        internal static string ui_Settings_Import_Conflict_Replace {
            get {
                return ResourceManager.GetString("ui_Settings_Import_Conflict_Replace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip existing (Recommended).
        /// </summary>
        internal static string ui_Settings_Import_Conflict_Skip {
            get {
                return ResourceManager.GetString("ui_Settings_Import_Conflict_Skip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When entry already exists.
        /// </summary>
        internal static string ui_Settings_Import_ConflictStrategy {
            get {
                return ResourceManager.GetString("ui_Settings_Import_ConflictStrategy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock after inactivity.
        /// </summary>
        internal static string ui_Settings_LockOnIdleTimeout {
            get {
                return ResourceManager.GetString("ui_Settings_LockOnIdleTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock when app is minimized.
        /// </summary>
        internal static string ui_Settings_LockOnMinimize {
            get {
                return ResourceManager.GetString("ui_Settings_LockOnMinimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows lock screen.
        /// </summary>
        internal static string ui_Settings_LockOnWindowsLock {
            get {
                return ResourceManager.GetString("ui_Settings_LockOnWindowsLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Overridden via CLI to {0}).
        /// </summary>
        internal static string ui_Settings_Logging_CliOverride_Format {
            get {
                return ResourceManager.GetString("ui_Settings_Logging_CliOverride_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging level.
        /// </summary>
        internal static string ui_Settings_Logging_Level {
            get {
                return ResourceManager.GetString("ui_Settings_Logging_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open log folder.
        /// </summary>
        internal static string ui_Settings_Logging_OpenFolder {
            get {
                return ResourceManager.GetString("ui_Settings_Logging_OpenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutes.
        /// </summary>
        internal static string ui_Settings_Minutes {
            get {
                return ResourceManager.GetString("ui_Settings_Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QR preview scale.
        /// </summary>
        internal static string ui_Settings_QrPreviewScale {
            get {
                return ResourceManager.GetString("ui_Settings_QrPreviewScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x (e.g. 2.0).
        /// </summary>
        internal static string ui_Settings_QrPreviewScale_Hint {
            get {
                return ResourceManager.GetString("ui_Settings_QrPreviewScale_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset to defaults.
        /// </summary>
        internal static string ui_Settings_ResetToDefaults {
            get {
                return ResourceManager.GetString("ui_Settings_ResetToDefaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common.
        /// </summary>
        internal static string ui_Settings_Section_Common {
            get {
                return ResourceManager.GetString("ui_Settings_Section_Common", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging.
        /// </summary>
        internal static string ui_Settings_Section_Logging {
            get {
                return ResourceManager.GetString("ui_Settings_Section_Logging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Misc.
        /// </summary>
        internal static string ui_Settings_Section_Misc {
            get {
                return ResourceManager.GetString("ui_Settings_Section_Misc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string ui_Settings_Tab_About {
            get {
                return ResourceManager.GetString("ui_Settings_Tab_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup &amp; Restore.
        /// </summary>
        internal static string ui_Settings_Tab_Export {
            get {
                return ResourceManager.GetString("ui_Settings_Tab_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Misc.
        /// </summary>
        internal static string ui_Settings_Tab_Misc {
            get {
                return ResourceManager.GetString("ui_Settings_Tab_Misc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security.
        /// </summary>
        internal static string ui_Settings_Tab_Security {
            get {
                return ResourceManager.GetString("ui_Settings_Tab_Security", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string ui_Settings_Title {
            get {
                return ResourceManager.GetString("ui_Settings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup your password.
        /// </summary>
        internal static string ui_Setup_Password {
            get {
                return ResourceManager.GetString("ui_Setup_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlock.
        /// </summary>
        internal static string ui_Unlock {
            get {
                return ResourceManager.GetString("ui_Unlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlock using your password.
        /// </summary>
        internal static string ui_UnlockWith_Pwd {
            get {
                return ResourceManager.GetString("ui_UnlockWith_Pwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Windows Hello.
        /// </summary>
        internal static string ui_Use_Hello {
            get {
                return ResourceManager.GetString("ui_Use_Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Password.
        /// </summary>
        internal static string ui_Use_Password {
            get {
                return ResourceManager.GetString("ui_Use_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOTP Manager.
        /// </summary>
        internal static string ui_Window_Title_TOTP_Manager {
            get {
                return ResourceManager.GetString("ui_Window_Title_TOTP_Manager", resourceCulture);
            }
        }
    }
}
