<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace>TOTP.Avalonia.Desktop</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <SignAssembly>True</SignAssembly>
    <AssemblyOriginatorKeyFile>..\TOTP.Core\totp-sign-key.snk</AssemblyOriginatorKeyFile>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>

  <PropertyGroup Condition="$([MSBuild]::IsOSPlatform('Windows'))">
    <TargetFramework>net9.0-windows10.0.19041.0</TargetFramework>
    <DefineConstants>$(DefineConstants);TOTP_PLATFORM_WINDOWS</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition="$([MSBuild]::IsOSPlatform('OSX'))">
    <DefineConstants>$(DefineConstants);TOTP_PLATFORM_MACOS</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition="$([MSBuild]::IsOSPlatform('Linux'))">
    <DefineConstants>$(DefineConstants);TOTP_PLATFORM_LINUX</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia.Desktop" Version="12.1.0" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="12.1.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="9.0.7" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.7" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="9.0.7" />
    <PackageReference Include="Serilog" Version="4.3.0" />
  </ItemGroup>

  <ItemGroup>
    <AvaloniaResource Include="..\TOTP\Assets\Icons\app.ico" Link="Assets\Icons\app.ico" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TOTP.Camera.OpenCv\TOTP.Camera.OpenCv.csproj" />
    <ProjectReference Include="..\TOTP.Core\TOTP.Core.csproj" />
    <ProjectReference Include="..\TOTP.Infrastructure\TOTP.Infrastructure.csproj" />
    <ProjectReference Include="..\TOTP.UI.Avalonia.Shared\TOTP.UI.Avalonia.Shared.csproj" />
  </ItemGroup>

  <ItemGroup Condition="$([MSBuild]::IsOSPlatform('Windows'))">
    <PackageReference Include="OpenCvSharp4.runtime.win" Version="4.13.0.20260627" />
    <ProjectReference Include="..\TOTP.Platform.Windows\TOTP.Platform.Windows.csproj" />
  </ItemGroup>

  <ItemGroup Condition="$([MSBuild]::IsOSPlatform('OSX'))">
    <PackageReference Include="OpenCvSharp4.runtime.osx.arm64" Version="4.13.0.20260627" />
    <ProjectReference Include="..\TOTP.Platform.MacOS\TOTP.Platform.MacOS.csproj" />
    <ProjectReference Include="..\TOTP.Platform.Unix\TOTP.Platform.Unix.csproj" />
  </ItemGroup>

  <ItemGroup Condition="$([MSBuild]::IsOSPlatform('Linux'))">
    <PackageReference Include="OpenCvSharp4.official.runtime.linux-x64" Version="4.13.0.20260627" />
    <ProjectReference Include="..\TOTP.Platform.Linux\TOTP.Platform.Linux.csproj" />
    <ProjectReference Include="..\TOTP.Platform.Unix\TOTP.Platform.Unix.csproj" />
  </ItemGroup>

</Project>
